[config]
default_to_workspace = false

[env]
DATABASE_HOST = "${CARGO_MAKE_WORKING_DIRECTORY}/data"
DATABASE_USERNAME = "app"
DATABASE_PASSWORD = "passwd"
DATABASE_NAME = "app"
AUTH_TOKEN_TTL = 86400
DATABASE_URL = "postgresql:///${DATABASE_NAME}?host=${CARGO_MAKE_WORKING_DIRECTORY}/data&user=${DATABASE_USERNAME}&password=${DATABASE_PASSWORD}"
REDIS_HOST = "localhost"
REDIS_PORT = 6379
JAEGER_HOST = "localhost"
JAEGER_PORT = 6831


[tasks.before-build]
run_task = [{ name = ["compose-up", "migrate"] }]

[tasks.run]
dependencies = ["before-build"]
command = "cargo"
args = ["run", "${@}"]

[tasks.run-with-nix]
command = "nix"
args = ["run", ".#app", "${@}"]


### Development

[tasks.watch]
dependencies = ["before-build"]
run_task = [{ name = ["fmt", "clippy", "test"] }]
watch = true

[tasks.test]
command = "cargo"
args = [
  "nextest",
  "run",
  "--workspace",
  "--status-level",
  "all",
  "--test-threads=1",
  "--no-tests=pass",
]

[tasks.test-ci]
dependencies = ["before-build"]
run_task = "test"

[tasks.migrate]
script = '''
#!/usr/bin/env bash
until sqlx migrate run --source adapter/migrations; do
    sleep 1
done
'''

[tasks.psql]
command = "psql"
args = ["${DATABASE_URL}", "${@}"]

[tasks.initial-setup]
command = "psql"
args = ["${DATABASE_URL}", "-f", "db/initial_setup.sql"]

### process-compose

[tasks.compose-up]
dependencies = ["compose-down"]
command = "nix"
args = ["run", ".#dev", "--", "-D"]

[tasks.compose-down]
command = "process-compose"
args = ["down"]
ignore_errors = true
