[config]
default_to_workspace = false

[tasks.compose-up]
args = ["run", ".#dev", "--", "-D"]
command = "nix"
dependencies = ["compose-down"]

[tasks.compose-down]
args = ["down"]
command = "process-compose"
ignore_errors = true
