[config]
default_to_workspace = false

[env]
HOST = "0.0.0.0"
PORT = 8080
DATABASE_USERNAME = "app"
DATABASE_PASSWORD = "passwd"
DATABASE_NAME = "app"
DATABASE_PORT_OUTER = 5432
DATABASE_PORT_INNER = 5432
REDIS_PORT_OUTER = 6379
REDIS_PORT_INNER = 6379
AUTH_TOKEN_TTL = 86400
DATABASE_HOST = "localhost"
DATABASE_PORT = "${DATABASE_PORT_OUTER}"
DATABASE_URL = "postgresql://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}?user=${DATABASE_USERNAME}&password=${DATABASE_PASSWORD}"
REDIS_HOST = "localhost"
REDIS_PORT = "${REDIS_PORT_OUTER}"
JAEGER_HOST = "localhost"
JAEGER_PORT = 6831


[tasks.before-build]
run_task = [{ name = ["compose-up", "migrate"] }]

[tasks.run]
dependencies = ["before-build"]
command = "cargo"
args = ["run", "${@}"]

[tasks.run-with-nix]
command = "nix"
args = ["run", ".#app", "${@}"]


### Development

[tasks.watch]
dependencies = ["before-build"]
run_task = [{ name = ["fmt", "clippy", "test"] }]
watch = true

[tasks.test]
command = "cargo"
args = [
  "nextest",
  "run",
  "--workspace",
  "--status-level",
  "all",
  "--test-threads=1",
  "--no-tests=pass",
]

[tasks.test-ci]
dependencies = ["before-build"]
run_task = "test"


### Migration

[tasks.migrate]
script = '''
#!/usr/bin/env bash
until sqlx migrate run --source adapter/migrations; do
    sleep 1
done
'''

[tasks.sqlx]
command = "sqlx"
args = ["${@}", "--source", "adapter/migrations"]


### process-compose

[tasks.compose-up]
command = "nix"
args = ["run", ".#dev", "--", "-D"]

[tasks.compose-down]
command = "process-compose"
args = ["down"]
