[package]
name = "kernel"
version = "0.1.0"
edition = "2024"

[dependencies]
shared.workspace = true
async-trait.workspace = true
uuid.workspace = true
serde.workspace = true
sqlx.workspace = true
strum.workspace = true
