name: CI for book
on:
  push:
    branches: [main]
  pull_request:
    paths-ignore:
      - "README.md"
      - "frontend/**"

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Cache dependencies
        uses: Swatinem/rust-cache@v2

      - uses: cachix/install-nix-action@v30

      - uses: cachix/cachix-action@v15
        with:
          name: yadokani389

      - name: enable direnv
        run: echo "use flake" > .envrc

      - uses: aldoborrero/direnv-nix-action@v2
        with:
          use_nix_profile: true
          nix_channel: nixpkgs

      - name: Test
        run: cargo make test-ci

      - name: Clippy
        run: cargo clippy --all --all-targets -- -Dwarnings

      - name: Rustfmt
        run: cargo fmt --all --check

      - name: Check unused dependencies
        run: nix run nixpkgs#cargo-machete
