name: CI for book
on:
  workflow_dispatch:
  push:
    branches: [main]
    paths-ignore:
      - "README.md"
  pull_request:
    paths-ignore:
      - "README.md"

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Cache dependencies
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: './item-manager -> target'

      - uses: cachix/install-nix-action@v30

      - uses: cachix/cachix-action@v15
        with:
          name: yadokani389

      - name: Restore binary cache
        uses: ./.github/actions/binary-cache
        with:
          package: .#devShells.x86_64-linux.default

      - name: Test
        run: nix develop -c cargo make --cwd item-manager test-ci

      - name: Check format and lint
        run: nix flake check

      - name: Check unused dependencies
        working-directory: item-manager
        run: nix run nixpkgs#cargo-machete
