name: Rust CI

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - "item-manager/**"
      - "Cargo.toml"
      - "Cargo.lock"
      - ".github/workflows/rust_ci.yaml"
  pull_request:
    paths:
      - "item-manager/**"
      - "Cargo.toml"
      - "Cargo.lock"
      - ".github/workflows/rust_ci.yaml"

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1

jobs:
  rust:
    name: Rust CI
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: item-manager

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache Rust dependencies
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: './item-manager -> target'

      - name: Install Nix
        uses: cachix/install-nix-action@v30

      - name: Setup Cachix
        uses: cachix/cachix-action@v15
        with:
          name: yadokani389

      - name: Restore binary cache
        uses: ./.github/actions/binary-cache
        with:
          package: .#devShells.x86_64-linux.default

      - name: Run tests
        run: nix develop -c cargo make test-ci

      - name: Check format and lint
        run: nix flake check -L
        working-directory: .

      - name: Check unused dependencies
        run: nix run nixpkgs#cargo-machete
